version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-todo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_todo_db
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
